//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA_SAT_CSHARP.VISTA {
    
    
    public partial class WF_MENU_PRINCIPAL {
    }
}
